

DROP TABLE IF EXISTS `article`;
CREATE TABLE IF NOT EXISTS `article` (
  `idArticle` int NOT NULL AUTO_INCREMENT,
  `idCategories` int NOT NULL,
  `titreArticle` varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci NOT NULL DEFAULT '',
  `descriptionArticle` text CHARACTER SET utf32 COLLATE utf32_general_ci NOT NULL,
  `imageArticle` varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci NOT NULL DEFAULT '',
  `datepubArticle` date DEFAULT NULL,
  `actif` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`idArticle`),
  UNIQUE KEY `titreArticle` (`titreArticle`),
  KEY `FKidCategories` (`idCategories`),
  CONSTRAINT `FKidCategories` FOREIGN KEY (`idCategories`) REFERENCES `categories` (`idCategorie`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=80 DEFAULT CHARSET=utf32;

INSERT INTO `article` (`idArticle`, `idCategories`, `titreArticle`, `descriptionArticle`, `imageArticle`, `datepubArticle`, `actif`) VALUES
	(67, 38, 'Hotel Berkshire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.', './upload/article/Hotel Berkshire.jpg', '2023-09-11', 1),
	(68, 39, 'Camp Sauvage', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.', './upload/article/Camp Sauvage.jpg', '2023-09-11', 1),
	(69, 38, 'Berkshire Ressorts', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.', './upload/article/Berkshire Ressorts.jpg', '2023-09-11', 1),
	(70, 38, 'Berkshire Palace', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.', './upload/article/Berkshire Palace.jpg', '2023-09-11', 1),
	(71, 38, 'Hotel Mariott', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.', './upload/article/Hotel Mariott.jpg', '2023-09-11', 1),
	(72, 40, 'Reposoire du Sacre-Coeur', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Phasellus fermentum malesuada phasellus netus dictum aenean placerat egestas amet. Ornare taciti semper dolor tristique morbi. Sem leo tincidunt aliquet semper eu lectus scelerisque quis. Sagittis vivamus mollis nisi mollis enim fermentum laoreet.Curabitur semper venenatis lectus viverra ex dictumst nulla maximus. Primis iaculis elementum conubia feugiat venenatis dolor augue ac blandit nullam ac phasellus turpis feugiat mollis. Duis lectus porta mattis imperdiet vivamus augue litora lectus arcu. Justo torquent pharetra volutpat ad blandit bibendum accumsan nec elit cras luctus primis ipsum gravida class congue.', './upload/article/Reposoire du Sacre-Coeur.jpg', '2023-09-11', 1),
	(73, 40, 'Reposoire Pelicans', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Phasellus fermentum malesuada phasellus netus dictum aenean placerat egestas amet. Ornare taciti semper dolor tristique morbi. Sem leo tincidunt aliquet semper eu lectus scelerisque quis. Sagittis vivamus mollis nisi mollis enim fermentum laoreet.Curabitur semper venenatis lectus viverra ex dictumst nulla maximus. Primis iaculis elementum conubia feugiat venenatis dolor augue ac blandit nullam ac phasellus turpis feugiat mollis. Duis lectus porta mattis imperdiet vivamus augue litora lectus arcu. Justo torquent pharetra volutpat ad blandit bibendum accumsan nec elit cras luctus primis ipsum gravida class congue.', './upload/article/Reposoire Pelicans.jpg', '2023-09-11', 1),
	(74, 39, 'Island Malty', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Phasellus fermentum malesuada phasellus netus dictum aenean placerat egestas amet. Ornare taciti semper dolor tristique morbi. Sem leo tincidunt aliquet semper eu lectus scelerisque quis. Sagittis vivamus mollis nisi mollis enim fermentum laoreet.Curabitur semper venenatis lectus viverra ex dictumst nulla maximus. Primis iaculis elementum conubia feugiat venenatis dolor augue ac blandit nullam ac phasellus turpis feugiat mollis. Duis lectus porta mattis imperdiet vivamus augue litora lectus arcu. Justo torquent pharetra volutpat ad blandit bibendum accumsan nec elit cras luctus primis ipsum gravida class congue.', './upload/article/Island Malty.jpg', '2023-09-11', 1),
	(75, 41, 'Les palmes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Phasellus fermentum malesuada phasellus netus dictum aenean placerat egestas amet. Ornare taciti semper dolor tristique morbi. Sem leo tincidunt aliquet semper eu lectus scelerisque quis. Sagittis vivamus mollis nisi mollis enim fermentum laoreet.Curabitur semper venenatis lectus viverra ex dictumst nulla maximus. Primis iaculis elementum conubia feugiat venenatis dolor augue ac blandit nullam ac phasellus turpis feugiat mollis. Duis lectus porta mattis imperdiet vivamus augue litora lectus arcu. Justo torquent pharetra volutpat ad blandit bibendum accumsan nec elit cras luctus primis ipsum gravida class congue.', './upload/article/Les palmes.jpg', '2023-09-11', 1),
	(76, 40, 'Reposoire Katyal', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Phasellus fermentum malesuada phasellus netus dictum aenean placerat egestas amet. Ornare taciti semper dolor tristique morbi. Sem leo tincidunt aliquet semper eu lectus scelerisque quis. Sagittis vivamus mollis nisi mollis enim fermentum laoreet.Curabitur semper venenatis lectus viverra ex dictumst nulla maximus. Primis iaculis elementum conubia feugiat venenatis dolor augue ac blandit nullam ac phasellus turpis feugiat mollis. Duis lectus porta mattis imperdiet vivamus augue litora lectus arcu. Justo torquent pharetra volutpat ad blandit bibendum accumsan nec elit cras luctus primis ipsum gravida class congue.', './upload/article/Reposoire Katyal.jpg', '2023-09-11', 1),
	(78, 41, 'Viaje du manitoba', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Phasellus fermentum malesuada phasellus netus dictum aenean placerat egestas amet. Ornare taciti semper dolor tristique morbi. Sem leo tincidunt aliquet semper eu lectus scelerisque quis. Sagittis vivamus mollis nisi mollis enim fermentum laoreet.Curabitur semper venenatis lectus viverra ex dictumst nulla maximus. Primis iaculis elementum conubia feugiat venenatis dolor augue ac blandit nullam ac phasellus turpis feugiat mollis. Duis lectus porta mattis imperdiet vivamus augue litora lectus arcu. Justo torquent pharetra volutpat ad blandit bibendum accumsan nec elit cras luctus primis ipsum gravida class congue.', './upload/article/Viaje du manitoba.jpg', '2023-09-11', 1),
	(79, 38, 'Dominicus Beach Kingdom', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. Pharetra vestibulum posuere ornare faucibus fusce dictumst orci aenean eu facilisis ut volutpat commodo senectus purus himenaeos fames primis convallis nisi.Phasellus fermentum malesuada phasellus netus dictum aenean placerat egestas amet. Ornare taciti semper dolor tristique morbi. Sem leo tincidunt aliquet semper eu lectus scelerisque quis. Sagittis vivamus mollis nisi mollis enim fermentum laoreet.Curabitur semper venenatis lectus viverra ex dictumst nulla maximus. Primis iaculis elementum conubia feugiat venenatis dolor augue ac blandit nullam ac phasellus turpis feugiat mollis. Duis lectus porta mattis imperdiet vivamus augue litora lectus arcu. Justo torquent pharetra volutpat ad blandit bibendum accumsan nec elit cras luctus primis ipsum gravida class congue.', './upload/article/Dominicus Beach Kingdom.jpg', '2023-09-11', 1);



DROP TABLE IF EXISTS `commentaires`;
CREATE TABLE IF NOT EXISTS `commentaires` (
  `idCommentaire` int NOT NULL AUTO_INCREMENT,
  `idArticle` int NOT NULL,
  `descriptionCommentaire` text CHARACTER SET utf32 COLLATE utf32_general_ci,
  `statut` tinyint DEFAULT NULL,
  PRIMARY KEY (`idCommentaire`) USING BTREE,
  KEY `FKIDArticle` (`idArticle`),
  CONSTRAINT `FKIDArticle` FOREIGN KEY (`idArticle`) REFERENCES `article` (`idArticle`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf32;


INSERT INTO `commentaires` (`idCommentaire`, `idArticle`, `descriptionCommentaire`, `statut`) VALUES
	(24, 68, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin tortor purus platea sit eu id nisi litora libero. Neque vulputate consequat ac amet augue blandit maximus aliquet congue. ', 1),
	(25, 70, 'C&#039;est tres beau', 1),
	(26, 73, 'Je suis un photographe amateur, et cet article m&#039;a donn&eacute; une nouvelle perspective sur la composition. J&#039;ai h&acirc;te de mettre en pratique ces astuces lors de ma prochaine sortie photo.', 1),
	(27, 73, 'L&#039;auteur a un talent incroyable pour expliquer des concepts complexes de mani&egrave;re simple et accessible. C&#039;est exactement ce dont j&#039;avais besoin pour am&eacute;liorer mes comp&eacute;tences en photographie.', 1);


DROP TABLE IF EXISTS `temoignages`;
CREATE TABLE IF NOT EXISTS `temoignages` (
  `idTemoignages` int NOT NULL AUTO_INCREMENT,
  `avis` text CHARACTER SET utf32 COLLATE utf32_general_ci NOT NULL,
  `image` varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci NOT NULL,
  `temoin` varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci NOT NULL,
  `statut` tinyint NOT NULL,
  `datepubTemoignage` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`idTemoignages`),
  UNIQUE KEY `temoin` (`temoin`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf32 COMMENT='Liste de tous les temoignages';


INSERT INTO `temoignages` (`idTemoignages`, `avis`, `image`, `temoin`, `statut`, `datepubTemoignage`) VALUES
	(6, 'L&#039;h&ocirc;tel &eacute;tait un petit bijou au c&oelig;ur de la ville. L&#039;&eacute;l&eacute;gance du lieu et le service attentionn&eacute; nous ont enchant&eacute;s.', './upload/avatar/Jane.jpg', 'Jane', 1, 1694444887),
	(7, 'Bravo pour ce blog incroyable ! Votre passion et votre d&eacute;vouement sont inspirants. Continuez &agrave; partager votre expertise avec le monde.', './upload/avatar/John Doe.jpg', 'John Doe', 1, 1694445157),
	(8, 'Je voulais simplement vous dire &agrave; quel point j&#039;appr&eacute;cie votre blog. Vos conseils sont pr&eacute;cieux, et votre enthousiasme est contagieux. Continuez &agrave; briller', './upload/avatar/Laura.png', 'Laura', 1, 1694446229),
	(9, 'Votre blog est devenu ma source pr&eacute;f&eacute;r&eacute;e d&#039;informations et de motivation. Merci de nous rappeler que nous pouvons accomplir de grandes choses', './upload/avatar/rickyto.jpg', 'rickyto', 1, 1694446270),
	(10, 'Je suis &eacute;pat&eacute;e par la qualit&eacute; de vos articles. Vous avez un don pour rendre des sujets complexes accessibles. Continuez &agrave; nous &eacute;duquer.', './upload/avatar/Sophie.png', 'Sophie', 1, 1694448620),
	(11, 'Votre blog est une bouff&eacute;e d&#039;air frais. Vos id&eacute;es sont innovantes et vos encouragements sont un v&eacute;ritable moteur. Continuez &agrave; nous surprendre.', './upload/avatar/Thomas.jpg', 'Thomas', 1, 1694450685),
	(12, 'Votre blog est un phare dans la mer de l&#039;information en ligne. Continuez &agrave; &eacute;clairer notre chemin vers le succ&egrave;s.', './upload/avatar/David.jpg', 'David', 1, 1694451309),
	(13, 'Votre blog est une source inestimable de motivation. Continuez &agrave; inspirer et &agrave; encourager les autres &agrave; poursuivre leurs r&ecirc;ves.', './upload/avatar/Anne.jpg', 'Anne', 1, 1694474604);


DROP TABLE IF EXISTS `utilisateur`;
CREATE TABLE IF NOT EXISTS `utilisateur` (
  `idUser` int NOT NULL AUTO_INCREMENT,
  `nomutilisateur` varchar(50) DEFAULT NULL,
  `motdepasse` varchar(50) DEFAULT NULL,
  `statut` tinyint DEFAULT NULL,
  PRIMARY KEY (`idUser`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf32 COMMENT='Les utilisateurs de l''application';


INSERT INTO `utilisateur` (`idUser`, `nomutilisateur`, `motdepasse`, `statut`) VALUES
	(1, 'admin', '1234', 1);


